### PR TITLE
Fix dependency vulnerability

### LINKED ISSUE #2563: npm install on master branch shows high vulnerability on cucumber
Hi,

When we run the `npm install` on the master branch, I noticed it shows there is one high vulnerability with the latest stable node/npm versions.

### Tools version:
- NPM version: 6.8.0
- Node version: v11.9.0
- OS: MacOS (Mojave)

### Steps to verify

- Clone the repository and be on master branch
- Run the `npm install`
- Gives following error:  `found 20 vulnerabilities (11 low, 6 moderate, 1 high, 2 critical)`
- Run `npm audit` and that gives you first fix for high vulnerabilities
- Run `npm install --save-dev cucumber@5.1.0`

The fix is very simple, just upgrade the version for cucumber to 5.1.0.

I have verified the tests using: `npm test` (ran all tests) and `npm run unit` (ran the unit tests)
This fix resolves the vulnerability.

I can provide a quick fix via PR

Regards,
Nagaraj

### PR DESCRIPTION
**Pull request by tan31989**
Fixes #2563
Quick fix for npm package high vulnerability.
The package which was showing high vulnerability was `cucumber`

Steps to reproduce is:
- Run the npm install
- Gives following error: found 20 vulnerabilities (11 low, 6 moderate, 1 high, 2 critical)
- Run npm audit and that gives you first fix for high vulnerabilities

##### Checklist

- [x] `npm run test` passes
- [x] changelog is added, `npm run add-change`

### CODE REVIEW

**Comment by tan31989** [comment]
Hi,

I see the failure is for node version `0.10.x`
In this case, since according to Node, the maintenance end date was **2016-10-31**, does it make sense to run the tests for the older version?

Regards,
Nagaraj

**Comment by AllanFly120** [comment]
Hey @tan31989 

Unfortunately dropping support of old node version requires further discussions. We prefer not to drop any node version we currently support(since 0.10).

**Comment by tan31989** [comment]
@AllanFly120 I will verify for the existing solution and get it fixed.

**Comment by tan31989** [comment]
@AllanFly120 I have downgraded the version but made sure the high vulnerability is removed. Let me know if something else is needed here.

**Comment by srchase** [comment]
@tan31989 

Thanks for submitting this issue and this PR.  

I went ahead and bumped other dev dependencies while resolving the issue in https://github.com/aws/aws-sdk-js/pull/2586

Thanks!!

**Pull request closed without merging**
