### PR TITLE
Fix/doc client empty nested members

### PR DESCRIPTION
**Pull request by jeskew**
This PR adds a couple tests to verify #1281 and protect against future regressions.

It also changes the expectations of some tests that assume that the system's path separator will be `/`, which was causing the unit test suite to fail on Windows.

/cc @chrisradek

### CODE REVIEW

**Comment by chrisradek** [comment]
:shipit:

**Comment by arun-gupta** [comment]
Similar value is not found in Java SDK: http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html Any idea when is that getting added?

**Comment by jeskew** [comment]
@arun-gupta You will need to open an issue on the [AWS SDK for Java repository](https://github.com/aws/aws-sdk-java).

**Comment by arun-gupta** [comment]
@jeskew thanks, just did!

**Pull request merged**
