### PR TITLE
Add getter and setter for external packages relying on AWS.CognitoIdentityCredentials.identityId

### LINKED ISSUE #1238: AWS.config.credentials.get() resets IdentityId to null when offline.
This particular use case is with a Cordova/PhoneGap enabled JavaScript app.

Steps to reproduce:

1. Call `AWS.config.credentials.get()`
2. Verify CognitoIdentityCredentials exists.
3. Close app.
4. Enable Airplane Mode / Disconnect Network
5. Launch app and call `AWS.config.credentials.get()`. Produces: `Error: Network Failure(…)`. Upon inspecting `AWS.config.credentials.identityId` ends up being `null`, even though I can still see a localStorage index for the identityId.

Shouldn't the last step use the cached IdentityID which was already retrieved?

### PR DESCRIPTION
**Pull request by jeskew**
Resolves #1238 

/cc @chrisradek

### CODE REVIEW

**Comment by johnborges** [comment]
@jeskew would you mind committing your branch? I'de like to test out your fix with my project.

**Comment by jeskew** [comment]
The branch is public on [my fork of this repo](https://github.com/jeskew/aws-sdk-js/tree/fix/ensure-cognito-identityId-always-loaded-from-cache-on-access). (If you're using webpack, you can install a specific branch from an arbitrary fork per the instructions [here](https://github.com/aws/aws-sdk-js/issues/603#issuecomment-244189509)).

**Comment by johnborges** [comment]
Thanks. I can confirm this fix is working for me.

**Comment by chrisradek** [comment]
:shipit:

**Pull request merged**
