### PR TITLE
Fix cross region bucket truncation

### PR DESCRIPTION
**Pull request by chrisradek**
The following code reproduces the issue:
```javascript
const S3 = require('aws-sdk/clients/s3');
const s3 = new S3({region: 'us-west-2'});

s3.putObject({
  Bucket: 'bucket-not-in-us-west-2',
  Key: 'bucket-not-in-us-west-2/foo/bar'
}, console.log);
```

In this case, the result is the object `foo/bar` in `bucket-not-in-us-west-2` instead of the object `bucket-not-in-us-west-2/foo/bar`.

This only happens if the region the S3 client is configured to use differs from the region the S3 bucket is actually in. When the SDK populates the URI and uses virtual-hosted style addressing, it removes the bucket from the path. Then, if a cross-region call is made and a redirect received, the SDK populates the URI again. However, since the path is still modified from the 1st request, it attempts to remove the bucket name from the path again. Since the object key prefix matches the bucket name, that part of the prefix is removed.

This update adds the bucket name back to the path after a cross-region call fails, if it would have been removed during the original call.

### CODE REVIEW

**Comment by AllanFly120** [comment]
One more note: Why didn't you differentiate the bucket name from the key in the path [here](https://github.com/aws/aws-sdk-js/pull/2199/files#diff-6046dafdd0a65a4b3489eda24e3dfe78L244) and make sure only bucket is removed? Will this also solve the issue?

**Comment by chrisradek** [comment]
On your note, I initially didn't do that because:
1. `Key` isn't required for all operations, so I was worried there could be cases where other parts of the URI were stripped. However, looking through all the operations, it looks like that is essentially a non-issue since you can't create buckets that contain question marks.

2. The object key is escaped before being inserted into the URI. That means we'd have to check if the Key parameter exists on the operation, escape it, and then exit early if the Key matches. This would be fine to do as long as new operations don't change some of our current assumptions about how Key is used (such as not being modeled with a `+` to indicate we should split the Key before escaping it).

So after digging more, making the change where you indicated would pass the tests, and should be fine in the future. It just seemed potentially more fragile if the model was updated in a way we didn't anticipate.

**Comment by chrisradek** [comment]
After thinking over your suggestion, I actually like the change you suggested better. Since this is a restful service, it's very unlikely we would see a change in the requestUri of an operation that would break our assumptions. Updated!

**Comment by AllanFly120** [comment]
re-shipit!

**Pull request merged**
