### PR TITLE
Use latest (successfully building) version of uuid

### PR DESCRIPTION
**Pull request by jrencz**
Removes one of 2 warnings mentioned in #3812

The way `uuid` is used in 
https://github.com/aws/aws-sdk-js/blob/bb861ce64a14f1d7f90d045481861d1b0de6cbde/lib/util.js#L920-L927
was already compatible with latest version

##### Checklist

- [x] `npm run test` passes

On `npm run test` passes`: `master` before this change when `npm run unit` is run @ node 16.2:
 2882 passing (18s)
  7 failing

With this PR:
 2882 passing (15s)
  7 failing

On `npm run integration` run @ node 16.2 same 4 problems are raised with and without uuid version bump.
No test was fixed, no test was broken.

### CODE REVIEW

**Review by BourgoisMickael — APPROVED** [review]

**Comment by BourgoisMickael** [comment]
@AllanZhengYP @trivikr Can you check this 1 line PR, shouldn't be hard to merge

**Comment by davecarlson** [comment]
@BourgoisMickael  - The CI build failed, you might want to take a look so we can get this merged in !

**Comment by jrencz** [comment]
@davecarlson I rebased to curent master.

I tried to run `npm run test` locally, but all I can say is "different year, same story

 4447 passing (22s)
  7 failing

just that now there's twice as much tests, but some stubborn 7 keep failing locally on node 16
For some reason I'm not able to install node 12 (as expressed in `buildspec.yml`) on the computer I have (Mac with M1 chip)

Let's see what will it be this time on CodeBuild

**Comment by jrencz** [comment]
@davecarlson t seems to [fail on CodeBuild|https://us-west-2.codebuild.aws.amazon.com/project/eyJlbmNyeXB0ZWREYXRhIjoiSUVHWlJaWndBekRwQkkxcnZxZ3JTZXVEeUN3SnVicFh3dGh4OWpNQytIYXl5Z3VQU053Zkh6ckpLZVc3OXdjaHZHODVCWElkeWRraWRaVmh4NjcvczZqYjREcDdndmR5cCtPL2FQOTQiLCJpdlBhcmFtZXRlclNwZWMiOiJsUjFwY2ZCL2ZrZVRVa1JkIiwibWF0ZXJpYWxTZXRTZXJpYWwiOjF9/build/b3cde6e7-1226-4972-8777-735383d88917?tab=buildLogs] for different reasons than locally - there are no failed tests. There's failure during minification of code run by a rake task

```ruby
  task :build_all => [:setup_dist_tools, :dist_path] do
    sh({"MINIFY" => "1"}, "#{$BUILDER} all > dist/aws-sdk-all.js")
  end
```

I tried running that locally and indeed with 8.3.2 it fails.

I bisected versions down and it turns out the latest that passes that step is [8.0.0|https://github.com/uuidjs/uuid/blob/main/CHANGELOG.md#800-2020-04-29]

Next one [8.1.0|https://github.com/uuidjs/uuid/blob/main/CHANGELOG.md#810-2020-05-20] fails.

There's a significant amount of changes [from v8.0.0 to v8.1.0 in uuid|https://github.com/uuidjs/uuid/compare/v8.0.0..v8.1.0] including some dependencies.

My best guess is that either one of those changes, or change in either of dependencies use some ES6 syntax that uglify doesn't like.

I have tried latest `uglify-js@2` - no progress.

I see it this way: we go with highest possible (i.e. 8.0.0) now. I wouldn't expect it ever to become gracefully minified with old `uglify-js`. Especially that `uuid` had no releases for months.

Let's build it with 8.0.0

**Comment by davecarlson** [comment]
Whoop it passes !

@BourgoisMickael @AllanZhengYP @trivikr can you take another look for code reviewers approval ?

**Review by BourgoisMickael — APPROVED** [review]

**Review by ajredniwja — APPROVED** [review]

**Pull request merged**
