### PR TITLE
Add/resume multi upload

### PR DESCRIPTION
**Pull request by chrisradek**
@AdityaManohar @dconnolly

### CODE REVIEW

**Comment by lonormaly** [comment]
Thanks! Is this version available on 2.2.4?

**Comment by dconnolly** [comment]
2.2.4 was released a week before these changes were merged in.

**Comment by kentor** [comment]
Is "resuming" supposed to work after an `abort()`?

**Comment by chrisradek** [comment]
@kentor 
Resuming should work after an abort if the upload was configured so `leavePartsOnError` was set to `true`.

**Comment by dconnolly** [comment]
== @chrisradek

**Pull request merged**
