### PR TITLE
Adds .tesselinclude for deployment inclusion of apis/*.json files. Fixes gh-967

### PR DESCRIPTION
**Pull request by rwaldron**
Signed-off-by: Rick Waldron <waldron.rick@gmail.com>

### CODE REVIEW

**Comment by rwaldron** [comment]
This travis failure seems unrelated? Please let me know if that's not the case

**Comment by rwaldron** [comment]
@chrisradek oh, it's possible yes. I should update this to be sure. I will do a sweep for other fs operations.

**Comment by rwaldron** [comment]
I've added a rule for `lib/services/*.js`—are there any other resources that might be necessary, but specifically `require(...)`'ed?

**Comment by chrisradek** [comment]
@rwaldron 
Sorry for the delay, merging this in!

**Pull request merged**
