### PR TITLE
Move sensitive to "value" instead of Map shape

### PR DESCRIPTION
**Pull request by hannesvdvreken**
##### Checklist

- [x] `npm run test` passes
- [x] run `npm run integration` if integration test is changed
- [x] `.d.ts` file is updated
- [x] changelog is added, `npm run add-change`
- [x] run `bundle exec rake docs:api` and inspect `doc/latest/index.html` if documentation is changed
- [x] non-code related change (markdown/git settings etc)

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
Problem:

When enabled logger to log info from the Cognito Identity Service Provider this happens:

```
12:31:04 0|d4h-sso  | [ 'login' ] Signing user in...
12:31:04 0|d4h-sso  | [
12:31:04 0|d4h-sso  |   '[AWS cognitoidentityserviceprovider 200 0.272s 0 retries] initiateAuth({\n' +
12:31:04 0|d4h-sso  |     "  ClientId: '***SensitiveInformation***',\n" +
12:31:04 0|d4h-sso  |     "  AuthFlow: 'USER_PASSWORD_AUTH',\n" +
12:31:04 0|d4h-sso  |     "  AuthParameters: { USERNAME: 'test-user', PASSWORD: 'EZ4zJ1R?' }\n" +
12:31:04 0|d4h-sso  |     '})'
```

Which means the password is never obscured.
The reason for this is the secure boolean is set on the MAP of AuthParameters but this has no influence. Secure only has influence on types that are not "map", "list" or "structure"s.

https://github.com/aws/aws-sdk-js/blob/master/lib/event_listeners.js#L532-L543

**Comment by hannesvdvreken** [comment]
@trivikr @AllanFly120 please tag this urgent / sensitive / security related.

**Comment by richardhboyd** [comment]
Het Hannes, these are automatically generated by an internal tool so this PR probably can't be merged, but I take your point about the information being exposed. I'm working with our JS SDK team on the best way to address it.

**Comment by ajredniwja** [comment]
This PR cant be merged as pointed out by @richardhboyd  but working with the team to address this as soon as possible.

**Comment by ajredniwja** [comment]
Hey @hannesvdvreken thank-you for your patience, in investigation found out that it is a BUG with the SDK which will be fixed at the earliest by the team and API model change will be requested from the service team wherever it is necessary.

**Comment by hannesvdvreken** [comment]
To not require the API model changes we can sort of find a way to inherit the "sensitive" flag from its ancestors? This way all the "map", "list" or "structure" which have the "sensitive" flag could have all its child nodes obscured in the logs.

**Comment by richardhboyd** [comment]
@hannesvdvreken when they say "API model change" they're referring to an internal API Model that is used as input to our tool to generate these definitions. My understanding is that the internal model would make some changes but the only changes customers would see would be similar to what you produced in the pull-request. (though created programmatically)

**Comment by hannesvdvreken** [comment]
> they're referring to an internal API Model that is used as input to our tool to generate these definitions

Yes exactly. I think it will require time and pinging a lot of people to act, so I was thinking of a way to avoid that.

Different question: would this update existing API Models which are tagged with their dates, or create entirely new tagged API Models?

**Comment by AllanFly120** [comment]
Hi @hannesvdvreken 

I have created a PR fixing the bugs with the SDK logger. Specifically, with this change, SDK will redact the senstive structure, maps, and lists. You are welcome to leave comments there.

> would this update existing API Models which are tagged with their dates, or create entirely new tagged API Models?

Only existing API models will be updated. The new tagged API models are for breaking API changes.

**Comment by ajredniwja** [comment]
@richardhboyd @hannesvdvreken There might be a confusion here, I mentioned API model changes from the service teams thinking about marking sensitive information as sensitive in their API models. I may still require to do some audit to check if everything is marked correctly. 

The PR #3350 has been approved and it should take care of the original issue.

**Comment by trivikr** [comment]
Update: v2.714.1 is released with the fix https://github.com/aws/aws-sdk-js/releases/tag/v2.714.1

**Pull request closed without merging**
