### PR TITLE
AWS.SharedIniFileCredentials loadRoleProfile using non existent optio…

### PR DESCRIPTION
**Pull request by dpmallinger**
AWS.SharedIniFileCredentials loadRoleProfile using non existent options #2197

updated the constructor to save this.options
updated the constructor to honor process.env.AWS_SHARED_CREDENTIALS_FILE

### CODE REVIEW

**Comment by srchase** [comment]
@dpmallinger 

What's your use case for saving options?

**Comment by dpmallinger** [comment]
@srchase 

Hello,

I believe I had a situation where I passed an aws profile as a parameter in options that needed to then be passed into the AWS.SharedIniFileCredentials instantiation ( line 233 of the same file ).    

var sourceCredentials = new AWS.SharedIniFileCredentials(
AWS.util.merge(this.options || {}, {
profile: sourceProfileName,
preferStaticCredentials: true
})
);

Its been a while and the exact use case is a bit fuzzy.

**Comment by ozankaya** [comment]
Use-case:

When we create a credentials object with options:
```
const credentials = new aws.SharedIniFileCredentials({
    filename: '/path/to/credentials',
});
```

The same options that are passed to **SharedIniFileCredentials** in the constructor should later be used in the same file, [here](https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/shared_ini_file_credentials.js#L229):

```
var sourceCredentials = new AWS.SharedIniFileCredentials(
    AWS.util.merge(this.options || {}, {
        profile: sourceProfileName,
        preferStaticCredentials: true
    })
);
```

Otherwise, it is failing to assume the role where credentials config is available in **/path/to/credentials**

**Comment by ajredniwja** [comment]
@dpmallinger Is this still a valid PR? Can the conflicts be resolved if it is?

**Comment by dpmallinger** [comment]
Hello @ajredniwja 

This appears to still be a valid issue.   The comment by @ozankaya best describes the problem. 

I went ahead and resolved the merge conflict.

**Comment by ajredniwja** [comment]
Can you address the build failure @dpmallinger

**Comment by dpmallinger** [comment]
@ajredniwja I re-merged aws/aws-sdk-js master into dpmallinger/aws-sdk-js master and the build failures still exists.  I don't understand enough about github and what is going on under the scenes to know why this 1 line change would produce so many failures.

**Comment by RanVaknin** [comment]
Closing for inactivity. This is very old.

**Pull request closed without merging**
