### PR TITLE
Remove querystring dependency

### LINKED ISSUE #4150: querystring package is deprecated.  Use URLSearchParams instead.
### Describe the bug

Library depends on "querystring" that is being deprecated.

https://www.npmjs.com/package/querystring

### Expected Behavior

"new code should use the URLSearchParams API instead"

### Current Behavior

npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

### Reproduction Steps

`npm install`

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### SDK version used

2.1171.0

### Environment details (OS name and version, etc.)

OS

### PR DESCRIPTION
**Pull request by samuelfullerthomas**
Partialy fixes #4150, #4466 & #4347 by removing the `querystring` dependency. `querystring` is still used by `url`, but that could be addressed in a follow up PR.

##### Checklist

- [x] `npm run test` passes
- [x] changelog is added, `npm run add-change`

### CODE REVIEW

**Comment by samuelfullerthomas** [comment]
I think to actually get rid of query string, `url` also needs to be removed, but I'd prefer to do that in a separate PR since it's a bit more elaborate

**Review by mkadirtan — APPROVED** [review]

**Comment by samuelfullerthomas** [comment]
@ajredniwja any chance of a review on this?

**Comment by jpike88** [comment]
@trivikr @kuhe happy new year guys, can this be looked at pls, it's a deprecated dependency

**Comment by tonedef** [comment]
Would love to know there's been an update on this. We can't use `aws-sdk` because this dependency conflicts with one of our security policies. 

BTW, thanks for doing this @samuelfullerthomas !

**Comment by boian-ivanov** [comment]
Is anyone still looking into merging this in? I'd be great to remove this depreciated package & the warning along with it

**Comment by pshenmic** [comment]
Hey, guys, bump this, or packages using aws-sdk is failed with npm security audit

**Comment by thukabjj** [comment]
Hi guys! could you bump this issue? Since it's a minor change over the lib it could be address faster

**Comment by samuelfullerthomas** [comment]
Won't fix: https://github.com/aws/aws-sdk-js/issues/4150

**Comment by fasihhussain00** [comment]
whyyyyyy?

**Review by fasihhussain00 — COMMENTED** [review]
lgtm

**Comment by fasihhussain00** [comment]
https://dev.to/sw360cab/migrating-aws-sdk-from-v2-to-v3-for-s3-32lh
I used this; I think it is good that AWS is providing separate libraries for each module rather than the whole SDK If one just want to use S3Client.
@samuelfullerthomas

**Pull request closed without merging**
