### PR TITLE
feat: bump yard to v0.9.26

### PR DESCRIPTION
**Pull request by trivikr**
Contains local version of the fix from https://github.com/lsegal/yard-js/pull/4

* The generated API reference can be viewed at https://aws-sd-js-3866-api-reference.netlify.app/
* The diff between output of `bundle exec rake docs:api` on master and this branch can be viewed at https://aws-sdk-js-3866-diff.netlify.app/

##### Checklist

- [x] non-code related change (markdown/git settings etc)

### CODE REVIEW

**Comment by trivikr** [comment]
The error is reported upstream at https://github.com/lsegal/yard-js/issues/3

```
[error]: Invalid configuration file, using default options.
[error]: FrozenError: can't modify frozen String
[error]: Stack trace:
	/local/home/trivikr/.rvm/gems/ruby-2.5.8/bundler/gems/yard-js-c76decbd26c9/lib/yard-js/core_ext/yard.rb:9:in `replace'
	/local/home/trivikr/.rvm/gems/ruby-2.5.8/bundler/gems/yard-js-c76decbd26c9/lib/yard-js/core_ext/yard.rb:9:in `<top (required)>'
	/local/home/trivikr/.rvm/gems/ruby-2.5.8/bundler/gems/yard-js-c76decbd26c9/lib/yard-js/plugin.rb:1:in `require_relative'
	/local/home/trivikr/.rvm/gems/ruby-2.5.8/bundler/gems/yard-js-c76decbd26c9/lib/yard-js/plugin.rb:1:in `<top (required)>'
	/local/home/trivikr/.rvm/gems/ruby-2.5.8/bundler/gems/yard-js-c76decbd26c9/lib/yard-js.rb:29:in `require_relative'
	/local/home/trivikr/.rvm/gems/ruby-2.5.8/bundler/gems/yard-js-c76decbd26c9/lib/yard-js.rb:29:in `<top (required)>'
```

However, it looks like yard-js is not maintained: The last release `v0.1.3` was on Jun 25, 2014 and there haven't been responses to issues cut after 2014.

**Comment by trivikr** [comment]
Attempted passing location of yard-js as per https://github.com/lsegal/yard-js/issues/1#issuecomment-33102259
```diff
     rm_rf "doc/latest"
     args = ENV['ARGS'] ? ENV['ARGS'] : []
-    sh "bundle exec yard #{args.join(' ')}"
+    yard_js_location = `gem which yard-js`
+    sh "bundle exec yard #{args.join(' ')} -e #{yard_js_location}"
   end
```

The error remains.

**Comment by trivikr** [comment]
Attempted removal of bumping ruby depdencies which are not yard as follows:

```diff
   remote: https://rubygems.org/
   specs:
     kpeg (1.1.0)
-    rake (13.0.6)
-    rdiscount (2.2.0.2)
+    rake (13.0.1)
+    rdiscount (2.1.7)
     redcarpet (3.5.1)
-    samus (3.0.9)
+    samus (1.4.1)
     yard-sitemap (1.0.1)
 
 PLATFORMS
@@ -42,4 +42,4 @@ DEPENDENCIES
   yard-sitemap (~> 1.0)
 
 BUNDLED WITH
-   1.17.3
+   1.14.6
```

The error remains.

**Comment by trivikr** [comment]
Attempted to run bundle exec with option `--enable-frozen-string-literal` as follows:

```console
RUBYOPT="--enable-frozen-string-literal" bundle exec rake docs:api
```

The error remains.

**Review by AllanZhengYP — APPROVED** [review]

**Pull request merged**
