### PR TITLE
Type FunctionError in Lambda InvocationResponse

### PR DESCRIPTION
**Pull request by LinusU**
Change the type from a generic string into an enum of the only two possible values.

### CODE REVIEW

**Comment by LinusU** [comment]
ping @chrisradek, any chance of getting this in? ☺️

**Comment by srchase** [comment]
This suggested change is on code generated from the resource model, which is managed by the Service Team. Those models cannot be changed from this repository. Thank you very much for this contribution, but we will need to close out this request.

**Comment by srchase** [comment]
@LinusU 

I've opened an internal request for the Lambda service team to review and consider updating their resource model to make this an enum.  

You're welcome to open your own request on their [AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=186).  If you link to that posting, I can update the internal request.

**Comment by srchase** [comment]
@LinusU 

This would be a breaking change and is not something that Lambda will be able to change on their API model.   For consistency between the SDKs and how those models are shared, we are not able to get make this an enum.

Appreciate you working with us on this and apologize that we didn't get it resolved sooner.

Thanks!

**Comment by LinusU** [comment]
I see, thanks for running it by the team ❤️

**Pull request closed without merging**
