### PR TITLE
fix: personalizeEventPropertiesJSON should be object

### PR DESCRIPTION
**Pull request by hideokamoto**
The pull request is a patch for the ticket -> AWS Personalize PutEvents - Error parsing properties json #2773

##### Checklist

- [x] `npm run test` passes
- [x] `.d.ts` file is updated
- [ ] changelog is added, `npm run add-change`
- [ ] run `bundle exec rake docs:api` and inspect `doc/latest/index.html` if documentation is changed
- [x] run `npm run integration` if integration test is changed
- [ ] non-code related change (markdown/git settings etc)

> Hi. I've got a similar error by using the SDK.
> 
> ## Environment
> ```
> $ node -v
> v10.16.0
> 
> $ npm -v 
> 6.9.0
> 
> $ cat package.json | jq .dependencies | grep aws-sdk
>   "aws-sdk": "^2.517.0",
> ```
> 
> ## DatasetSchema
> ```json
> {
> 	"name": "Interactions",
> 	"namespace": "com.amazonaws.personalize.schema",
> 	"type": "record",
> 	"fields": [
> 		{
> 			"name": "USER_ID",
> 			"type": "string"
> 		},
> 		{
> 			"name": "ITEM_ID",
> 			"type": "string"
> 		},
> 		{
> 			"name": "EVENT_TYPE",
> 			"type": "string"
> 		},
> 		{
> 			"name": "EVENT_VALUE",
> 			"type": "float"
> 		},
> 		{
> 			"name": "TIMESTAMP",
> 			"type": "long"
> 		},
> 		{
> 			"name": "SESSION_ID",
> 			"type": "string"
> 		}
> 	],
> 	"version": "1.0"
> }
> ```
> 
> ## Codes
> ### 1st try -> ERROR
> ```ts
> import {
>   PersonalizeEvents,
> } from 'aws-sdk'
> import { v4 } from 'uuid'
> import moment from 'moment'
> 
> const trackEvent = async () => {
>   const client = new PersonalizeEvents({
>     region: 'ap-northeast-1'
>   })
>   const params: PersonalizeEvents.Types.PutEventsRequest = {
>     trackingId: 'xxx-xxx-xxx-xxx',
>     userId: '1',
>     sessionId: v4(),
>     eventList: [{
>       eventId: v4(),
>       sentAt: moment().toDate(),
>       eventType: 'rating',
>       properties: JSON.stringify({
>         itemId: '1',
>         eventValue: 1.0
>       })
>     }]
>   }
>   console.log(params)
>   const result = await client.putEvents(params).promise()
>   console.log(result)
>   return
> }
> trackEvent()
> ```
> 
> #### Result
> ```shell
> $  ./node_modules/.bin/ts-node libs/index.ts 
> { trackingId: '52c88f57-7d7f-4941-8396-4c6a7434ec0d',
>   userId: '1',
>   sessionId: '4d58f851-6c8e-4ae8-8038-56f86f5f40ee',
>   eventList:
>    [ { eventId: 'd6ed382a-999e-4728-9895-98612a959506',
>        sentAt: 2019-08-25T14:57:30.307Z,
>        eventType: 'rating',
>        properties: '{"itemId":"1","eventValue":1}' } ] }
> 
> { InvalidInputException: Error parsing properties json
>     at Object.extractError (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/protocol/json.js:51:27)
>     at Request.extractError (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
>     at Request.callListeners (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
>     at Request.emit (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
>     at Request.emit (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/request.js:683:14)
>     at Request.transition (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/request.js:22:10)
>     at AcceptorStateMachine.runTo (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/state_machine.js:14:12)
>     at /Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/state_machine.js:26:10
>     at Request.<anonymous> (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/request.js:38:9)
>     at Request.<anonymous> (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/request.js:685:12)
>   message: 'Error parsing properties json',
>   code: 'InvalidInputException',
>   time: 2019-08-25T14:57:30.537Z,
>   requestId: 'd6766b7e-69b0-4889-83cf-18171e509b4a',
>   statusCode: 400,
>   retryable: false,
>   retryDelay: 65.34243647640349 }
> ```
> 
> ### 2nd try -> ERROR
> ```ts
> import {
>   PersonalizeEvents,
> } from 'aws-sdk'
> import { v4 } from 'uuid'
> import moment from 'moment'
> 
> const trackEvent = async () => {
>   const client = new PersonalizeEvents({
>     region: 'ap-northeast-1'
>   })
>   const params: PersonalizeEvents.Types.PutEventsRequest = {
>     trackingId: 'xxx-xxx-xxx-xxx',
>     userId: '1',
>     sessionId: v4(),
>     eventList: [{
>       eventId: v4(),
>       sentAt: moment().toDate(),
>       eventType: 'rating',
>       properties: {
>         itemId: '1',
>         eventValue: 1.0
>       }
>     }]
>   }
>   console.log(params)
>   const result = await client.putEvents(params).promise()
>   console.log(result)
>   return
> }
> trackEvent()
> ```
> 
> #### Result
> ```shell
> $  ./node_modules/.bin/ts-node libs/index.ts 
> 
> /Users/develop/sandbox//node_modules/ts-node/src/index.ts:245
>     return new TSError(diagnosticText, diagnosticCodes)
>            ^
> TSError: ⨯ Unable to compile TypeScript:
> libs/index.ts:34:7 - error TS2322: Type '{ itemId: string; eventValue: number; }' is not assignable to type 'string'.
> 
> 34       properties: {
>          ~~~~~~~~~~
> 
>   node_modules/aws-sdk/clients/personalizeevents.d.ts:37:5
>     37     properties: EventPropertiesJSON;
>            ~~~~~~~~~~
>     The expected type comes from property 'properties' which is declared here on type 'Event'
> ```
> 
> ### Final Try -> Success
> ```ts
> import {
>   PersonalizeEvents,
> } from 'aws-sdk'
> import { v4 } from 'uuid'
> import moment from 'moment'
> 
> const trackEvent = async () => {
>   const client = new PersonalizeEvents({
>     region: 'ap-northeast-1'
>   })
>   const params: PersonalizeEvents.Types.PutEventsRequest = {
>     trackingId: 'xxx-xxx-xxx-xxx',
>     userId: '1',
>     sessionId: v4(),
>     eventList: [{
>       eventId: v4(),
>       sentAt: moment().toDate(),
>       eventType: 'rating',
>       properties: {
>         itemId: '1',
>         eventValue: 1.0
>       } as any as PersonalizeEvents.Types.EventPropertiesJSON
>     }]
>   }
>   console.log(params)
>   const result = await client.putEvents(params).promise()
>   console.log(result)
>   return
> }
> trackEvent()
> ```
> 
> #### Result
> ```shell
> $  ./node_modules/.bin/ts-node libs/index.ts 
> { trackingId: '52c88f57-7d7f-4941-8396-4c6a7434ec0d',
>   userId: '1',
>   sessionId: 'dcaf9abd-db3b-4793-a43e-6bb9ce6a1f9a',
>   eventList:
>    [ { eventId: 'b938051a-bf9c-4e3c-8c9a-b0453bee46e5',
>        sentAt: 2019-08-25T14:59:26.639Z,
>        eventType: 'rating',
>        properties: [Object] } ] }
> {}
> ```
> 
> ## Problems
> I think the `PersonalizeEvents.Event` should be the following.
> 
> ### Wrong
> ```ts
> declare namespace PersonalizeEvents {
>   export type _Date = Date;
>   export interface Event {
>     /**
>      * An ID associated with the event. If an event ID is not provided, Amazon Personalize generates a unique ID for the event. An event ID is not used as an input to the model. Amazon Personalize uses the event ID to distinquish unique events. Any subsequent events after the first with the same event ID are not used in model training.
>      */
>     eventId?: StringType;
>     /**
>      * The type of event. This property corresponds to the EVENT_TYPE field of the Interactions schema.
>      */
>     eventType: StringType;
>     /**
>      * A string map of event-specific data that you might choose to record. For example, if a user rates a movie on your site, you might send the movie ID and rating, and the number of movie ratings made by the user. Each item in the map consists of a key-value pair. For example,  {"itemId": "movie1"}   {"itemId": "movie2", "eventValue": "4.5"}   {"itemId": "movie3", "eventValue": "3", "numberOfRatings": "12"}  The keys use camel case names that match the fields in the Interactions schema. The itemId and eventValue keys correspond to the ITEM_ID and EVENT_VALUE fields. In the above example, the eventType might be 'MovieRating' with eventValue being the rating. The numberOfRatings would match the 'NUMBER_OF_RATINGS' field defined in the Interactions schema.
>      */
>     properties: EventPropertiesJSON;
>     /**
>      * The timestamp on the client side when the event occurred.
>      */
>     sentAt: _Date;
>   }
>   export type EventList = Event[];
>   export type EventPropertiesJSON = string;
> ...
> ```
> 
> ### OK
> ```ts
> declare namespace PersonalizeEvents {
>   export type _Date = Date;
>   export interface Event {
>     /**
>      * An ID associated with the event. If an event ID is not provided, Amazon Personalize generates a unique ID for the event. An event ID is not used as an input to the model. Amazon Personalize uses the event ID to distinquish unique events. Any subsequent events after the first with the same event ID are not used in model training.
>      */
>     eventId?: StringType;
>     /**
>      * The type of event. This property corresponds to the EVENT_TYPE field of the Interactions schema.
>      */
>     eventType: StringType;
>     /**
>      * A string map of event-specific data that you might choose to record. For example, if a user rates a movie on your site, you might send the movie ID and rating, and the number of movie ratings made by the user. Each item in the map consists of a key-value pair. For example,  {"itemId": "movie1"}   {"itemId": "movie2", "eventValue": "4.5"}   {"itemId": "movie3", "eventValue": "3", "numberOfRatings": "12"}  The keys use camel case names that match the fields in the Interactions schema. The itemId and eventValue keys correspond to the ITEM_ID and EVENT_VALUE fields. In the above example, the eventType might be 'MovieRating' with eventValue being the rating. The numberOfRatings would match the 'NUMBER_OF_RATINGS' field defined in the Interactions schema.
>      */
>     properties: EventPropertiesJSON;
>     /**
>      * The timestamp on the client side when the event occurred.
>      */
>     sentAt: _Date;
>   }
>   export type EventList = Event[];
>   export type EventPropertiesJSON = {[key: string]: any};
> ...
> ```

### CODE REVIEW

**Comment by hideokamoto** [comment]
any update?

**Comment by ajredniwja** [comment]
Hey @hideokamoto thank-you for the pull request can you add the [change log](https://github.com/aws/aws-sdk-js/blob/master/CONTRIBUTING.md#user-content-changelog).

**Comment by hideokamoto** [comment]
@ajredniwja 
Hi!
I've create a change log in here.
https://github.com/aws/aws-sdk-js/pull/2821/files#diff-09f7a4a4e3c18801319c603def206407

Kindly regards.

**Comment by AllanFly120** [comment]
Hey @hideokamoto Thank you for the awesome deep dive on the issue. 

The TS definition file you are updating is generated, your fix won't be persistent in this SDK. They are generated from [the JSON model](https://github.com/aws/aws-sdk-js/blob/master/apis/personalize-events-2018-03-22.normal.json) by the [definition generator](https://github.com/aws/aws-sdk-js/blob/master/scripts/typings-generator.js). We need to update the generator to better handle the model. The root cause of the original issue is that the `"jsonValue": true` trait is not recognized by the TS def generator, so it assumes the member is a plain string. Instead, the trait means put the json member directly into the payload and set the media type header accordingly. 

I will close the PR for now and prioritize a fix from the SDK dev team.

**Comment by AllanFly120** [comment]
@hideokamoto 
As [in the comment from original issue](https://github.com/aws/aws-sdk-js/issues/2773#issuecomment-606775834), SDK team won't provide a fix. Other users can use the workaround you gave in the original issue, or adopt the V3 SDK.
You are still welcome to contribute to this feature. I already provide where you can start in my last comment. Please let me know if you need other help from me.

**Pull request closed without merging**
