### PR TITLE
Respect NODE_TLS_REJECT_UNAUTHORIZED environment variable under node

### LINKED ISSUE #1681: Upload to SQS fails with incorrect error when trying to upload to a bucket that does not exist
I have two buckets: 

`https://internal-msgs-svc-dev-xxxxx.us-west-2.elb.amazonaws.com/yyyy/zzzz` -- dev env (does not exist) (note that this url is totally wrong)

`https://sqs.us-west-2.amazonaws.com/xxxxxx/yyyyyy` - playground env (exists)

I think I copied the wrong url at some point and pasted it in to my config. When my code was trying to upload to it I was seeing a strange error about `self signed certificate` even though `NODE_TLS_REJECT_UNAUTHORIZED` was set to `0` when the app booted up. 

Here's the code: 

```
const AWS = require("aws-sdk");
const config = require("../config");
AWS.config.update(config.aws.enrichment.access);
const sqs = new AWS.SQS({apiVersion: "2012-11-05"});

const message = {hay: "for horses!"};
console.dir({NODE_TLS_REJECT_UNAUTHORIZED: process.env.NODE_TLS_REJECT_UNAUTHORIZED});

const msg = {
  MessageBody: JSON.stringify(message),
  QueueUrl: config.aws.enrichment.queueUrl
};

console.dir(msg);
console.log("Sending message...");
sqs.sendMessage(msg, (err, data) => {
  if (err) {
    console.log("Sending message downstream failed.");
    console.log("Failing message: ", msg.MessageBody);
    console.dir(err);
  } else {
    console.log("Message sent", data);
  }
});
```

Output: 

```
$ NODE_ENV=lab NODE_TLS_REJECT_UNAUTHORIZED=0 node ./etc/sqs-put.js
{ NODE_TLS_REJECT_UNAUTHORIZED: '0' }
{ MessageBody: '{"hay":"for horses!"}',
  QueueUrl: 'https://internal-msgs-svc-dev-xxxxx.us-west-2.elb.amazonaws.com/yyyy/zzzz' }
Sending message...
Sending message downstream failed.
Failing message:  {"hay":"for horses!"}
{ Error: self signed certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
  message: 'self signed certificate',
  code: 'NetworkingError',
  region: 'us-west-2',
  hostname: 'https://internal-msgs-svc-dev-xxxxx.us-west-2.elb.amazonaws.com/yyyy/zzzz',
  retryable: true,
  time: 2017-08-11T23:10:29.861Z }
```

The problem here is that it should have been telling me that I had an invalid url or something but instead it threw a cryptic error about "self signed certificate" while `NODE_TLS_REJECT_UNAUTHORIZED` was set to `0`.

### PR DESCRIPTION
**Pull request by bbeausej**
Under node, if the NODE_TLS_REJECT_UNAUTHORIZED environment variable is set to '0' ssl verification of peers should be disabled. This PR will make the sslAgent under node/http follow this convention.

This change will  allow the use of the SDK with a compatible storage layer using a self-signed certificate (like minio) in a testing environment.

Fixes #1681 

##### Checklist

- [x] `npm run test` passes
- [x] changelog is added, `npm run add-change`

### CODE REVIEW

**Comment by kimihiro64** [comment]
Would be nice to get this merged in, have a lot of self-signed certificate usecases that are affected by this right now

**Comment by AllanFly120** [comment]
@bbeausej Thank you for submitting the PR.  Can you add a unit test for it? You may add it [here](https://github.com/aws/aws-sdk-js/blob/master/test/node_http_client.spec.js)

**Comment by bbeausej** [comment]
@AllanFly120 tests added courtesy of @kimihiro64 

Let me know if you need anything else added!

**Comment by bbeausej** [comment]
Pinging this PR for merge inclusion. Is any else missing for this to get merged?

**Comment by jcgertig** [comment]
Bump

**Comment by bbeausej** [comment]
Anything else required for this merge / review to occur?

**Comment by c24w** [comment]
Any idea when this will make it into a release?  Literally just hit this issue :(

**Pull request merged**
